package com.brianway.learning.java8.effective.optional;

import com.brianway.learning.java8.effective.optional.Car;
import com.brianway.learning.java8.effective.optional.Insurance;
import com.brianway.learning.java8.effective.optional.OptionalMain;
import com.brianway.learning.java8.effective.optional.Person;
import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class OptionalMainTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java8/effective/optional/OptionalMain.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void findCheapestInsuranceInputNotNullNotNullOutputNotNull() {

    // Arrange
    OptionalMain objectUnderTest = new OptionalMain();
    Person person = new Person();
    Car car = new Car();

    // Act
    Insurance retval = objectUnderTest.findCheapestInsurance(person, car);

    // Assert result
    Assert.assertNotNull(retval);
    Assert.assertEquals(null, Reflector.getInstanceField(retval, "name"));
  }
}
