package com.brianway.learning.java.base.typeinfo;

import com.brianway.learning.java.base.typeinfo.FilledList;
import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.Array;
import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;

public class FilledListTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/base/typeinfo/FilledList.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *
   */

  @Test
  public void createInputZeroOutput0() throws InvocationTargetException {

    // Arrange
    FilledList objectUnderTest =
        ((FilledList)Reflector.getInstance("com.brianway.learning.java.base.typeinfo.FilledList"));
    Reflector.setField(objectUnderTest, "type", null);
    int nElements = 0;

    // Act
    List retval = objectUnderTest.create(nElements);

    // Assert result
    ArrayList arrayList = new ArrayList();
    Assert.assertEquals(arrayList, retval);
  }
}
