package com.brianway.learning.java8.streamapi.practice;

import com.brianway.learning.java8.streamapi.practice.Trader;
import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.InvocationTargetException;

public class TraderTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java8/streamapi/practice/Trader.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void toStringOutputNotNull() throws InvocationTargetException {

    // Arrange
    Trader objectUnderTest =
        ((Trader)Reflector.getInstance("com.brianway.learning.java8.streamapi.practice.Trader"));
    Reflector.setField(objectUnderTest, "city", "");
    Reflector.setField(objectUnderTest, "name", "!!!!");

    // Act
    String retval = objectUnderTest.toString();

    // Assert result
    Assert.assertEquals("Trader:!!!! in ", retval);
  }
}
