package com.brianway.learning.java.base.generics;

import com.brianway.learning.java.base.generics.GenericVarargs;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

public class GenericVarargsTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/base/generics/GenericVarargs.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - com/brianway/learning/java/base/generics/GenericVarargs.java:12: loop:
   * 1 iterations
   *  - iteration 1
   *     - conditional line 13 branch to line 13
   */

  @Test
  public void makeListInput1Output1() {

    // Arrange
    Object[] args = {null};

    // Act
    List retval = GenericVarargs.makeList(args);

    // Assert result
    ArrayList arrayList = new ArrayList();
    arrayList.add(null);
    Assert.assertEquals(arrayList, retval);
  }
}
