package com.brianway.learning.java.base.generics;

import com.brianway.learning.java.base.generics.Holder;
import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.InvocationTargetException;

public class HolderTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/base/generics/Holder.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 23 branch to line 23
   */

  @Test
  public void equalsInputNegativeOutputTrue() throws InvocationTargetException {

    // Arrange
    Holder objectUnderTest =
        ((Holder)Reflector.getInstance("com.brianway.learning.java.base.generics.Holder"));
    Reflector.setField(objectUnderTest, "value", -268_435_457);
    Object obj = -268_435_457;

    // Act
    boolean retval = objectUnderTest.equals(obj);

    // Assert result
    Assert.assertEquals(true, retval);
  }
}
