package com.brianway.learning.java.multithread.singleton.example3;

import com.brianway.learning.java.multithread.singleton.example3.MyObject3;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class MyObject3Test {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/multithread/singleton/example3/MyObject3.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void getInstanceOutputNotNull() {

    // Act
    MyObject3 retval = MyObject3.getInstance();

    // Assert result
    Assert.assertNotNull(retval);
  }
}
