package com.brianway.learning.java.multithread.singleton.example1;

import com.brianway.learning.java.multithread.singleton.example1.MyObject0;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class MyObject0Test {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/multithread/singleton/example1/MyObject0.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void getInstanceOutputNotNull() {

    // Act
    MyObject0 retval = MyObject0.getInstance();

    // Assert result
    Assert.assertNotNull(retval);
  }
}
