package com.brianway.learning.java.multithread.singleton.example1;

import com.brianway.learning.java.multithread.singleton.example1.MyObject1;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class MyObject1Test {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/multithread/singleton/example1/MyObject1.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - conditional line 14 branch to line 15
   */

  @Test
  public void getInstanceOutputNotNull() {

    // Act
    MyObject1 retval = MyObject1.getInstance();

    // Assert result
    Assert.assertNotNull(retval);
  }
}
