package com.brianway.learning.java.jvm.classloading;

import com.brianway.learning.java.jvm.classloading.SimpleClass;
import com.diffblue.deeptestutils.Reflector;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import java.lang.reflect.InvocationTargetException;

public class SimpleClassTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java/jvm/classloading/SimpleClass.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void incOutputZero() throws InvocationTargetException {

    // Arrange
    SimpleClass objectUnderTest = ((SimpleClass)Reflector.getInstance(
        "com.brianway.learning.java.jvm.classloading.SimpleClass"));
    Reflector.setField(objectUnderTest, "m", -1);

    // Act
    int retval = objectUnderTest.inc();

    // Assert result
    Assert.assertEquals(0, retval);
  }
}
