package com.brianway.learning.java8.streamapi.parallel;

import com.brianway.learning.java8.streamapi.parallel.ParallelStreams;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

public class ParallelStreamsTest {

  @Rule public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: com/brianway/learning/java8/streamapi/parallel/ParallelStreams.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers:
   *  - com/brianway/learning/java8/streamapi/parallel/ParallelStreams.java:17:
   * loop: 1 iterations
   */

  @Test
  public void iterativeSumInputZeroOutputZero() {

    // Arrange
    long n = 0L;

    // Act
    long retval = ParallelStreams.iterativeSum(n);

    // Assert result
    Assert.assertEquals(0L, retval);
  }
}
